### ISSUE TITLE
No longer working with Buidler

### ISSUE THREAD

**Issue by PaulRBerg** [crytic/crytic-compile#116]
## Description

There are projects that managed to integrate Buidler and Crytic Compile, like [fyDai](https://github.com/yieldprotocol/fyDai), but they are using older versions of the tools.

With a clean-slate repo, Buidler@1.4.8 and a basic Greeter.sol contract, this is the error that you're getting:

```
$ crytic-compile . --compile-force-framework buidler
INFO:CryticCompile:'npx buidler compile' running
INFO:CryticCompile:Compiling...
Compiled 2 contracts successfully

ERROR:CryticCompile:Unknown file: ontracts/Greeter.sol
```

## Steps to Reproduce

1. Fork [paulrberg/crytic-compile-bug][1]
2. Install dependencies with yarn
3. Run `crytic-compile . --compile-force-framework buidler`

## Environment

+ buidler@1.4.8
+ crytic-compile@0.1.9
+ solc@0.7.4

[1]: https://github.com/paulrberg/crytic-compile-bug

**Comment by PaulRBerg** [comment]
Possibly related to https://github.com/crytic/crytic-compile/issues/12.

**Comment by PaulRBerg** [comment]
I traced down the issue and it looks like the error is thrown here:

https://github.com/crytic/crytic-compile/blob/master/crytic_compile/utils/naming.py#L103

I wonder whether the fact that the first letter is sliced in the console log has something to do with this? It says "ontracts/Greeter.sol" not "contracts/Greeter.sol", as it should.

**Comment by rmi7** [comment]
Turns out, this is a bug inside Buidler. 

The `buidler compile` command creates a `cache/solc-output.json` file where the contract dir's first letter is chopped off, see line 26

![Screenshot 2020-10-21 at 17 07 48](https://user-images.githubusercontent.com/15264239/96741170-d4847b00-13c1-11eb-8706-86052ffa4e44.png)

We could fix it by prepending a `c` in slither. However, let's first find out where this bug got introduced, and also (in time)   in which version it got fixed. We can then fix it in slither by prepending a `c` (ugly hack) or display a warning when using a Buidler version with this bug.

**Comment by PaulRBerg** [comment]
You're right, @rmi7. I talked to @alcuadrado and he confirmed that this is a bug, but luckily for us, it's activated only the "root" path is set in `buidler.config.ts`. They're working on a fix.

What we should do in this repo is add a caveat in the repo about the "root" path. Users of crytic-compile should avoid it.

**Comment by rmi7** [comment]
Thanks for following this up @PaulRBerg. We will add such a note in a PR shortly, and will close this issue once it's merged!
