### ISSUE TITLE
If cwd is `/`, crytic-compile will strip too many characters from a path

### ISSUE THREAD

**Issue by elopez** [crytic/crytic-compile#310]
In this part, crytic-compile tries to "relativize" a path manually, but this does not do the right thing if cwd is `/`

https://github.com/crytic/crytic-compile/blob/0.2.4/crytic_compile/platform/solc.py#L502-L510

Execution with some printed variables:

```sh
root@33d8bea5df1f:/# cd /
root@33d8bea5df1f:/# crytic-compile -- /src/tests/solidity/basic/flags.sol
relative_path  /src/tests/solidity/basic/flags.sol
working_directory /
resulting command ['solc', '/src/tests/solidity/basic/flags.sol', '--combined-json', 'abi,ast,bin,bin-runtime,srcmap,srcmap-runtime,userdoc,devdoc,hashes,compact-format', '--allow-paths', '.', 'rc/tests/solidity/basic/flags.sol']
INFO:CryticCompile:Compilation warnings/errors on /src/tests/solidity/basic/flags.sol:
"rc/tests/solidity/basic/flags.sol" is not found.

ERROR:CryticCompile:Invalid solc compilation "rc/tests/solidity/basic/flags.sol" is not found.
```

We could consider replacing this with something like `pathlib.Path.(is_)relative_to`: https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.relative_to

Related: crytic/echidna#847 (the full path is correct but it does not work due to this issue, as the container working directory in that example is `/`)

**Comment by samalws-tob** [comment]
Currently working on this. The naive fix seems to be doing `relative_filepath = os.path.relpath(filename)`, but digging a little deeper into the issue:
- It seems like the current way we use `--allow-paths` is wrong. According to `solc --help`, `--allow-paths` should take a comma-separated list of arguments. So it should be `cmd += ["--allow-paths", ".," + relative_filepath]` rather than `cmd += ["--allow-paths", ".", relative_filepath]`.
- Does anyone know why we use `--allow-paths . relative_filepath` (or `--allow-paths .,relative_filepath`) rather than `--base-path . --include-path relative_filepath`? I'm trying out both and the latter seems to work more consistently in the examples I'm trying. I'm not too familiar with these solc arguments in general so I might be missing something.
